-- Local-only PostgreSQL schema for the SQLite productos source.
-- This file contains no destructive statements and is safe to re-run.

CREATE TABLE IF NOT EXISTS "productos" (
    "MARCA" TEXT,
    "CÓDIGO" TEXT PRIMARY KEY,
    "CÓDIGO WEB" TEXT,
    "REFERENCIA" TEXT,
    "EAN 13" DOUBLE PRECISION,
    "DESCRIPCION" TEXT,
    "U.P.LOG" DOUBLE PRECISION,
    "U.CAJA" INTEGER,
    "DTO." TEXT,
    "CLASE ETIM" TEXT,
    "RAEE_A" DOUBLE PRECISION,
    "RAEE_L" DOUBLE PRECISION,
    "RAEE_T" DOUBLE PRECISION,
    "Peso bruto KG" DOUBLE PRECISION,
    "Peso bruto GR" DOUBLE PRECISION,
    "Peso neto KG" DOUBLE PRECISION,
    "Peso neto GR" DOUBLE PRECISION,
    "Longitud M" DOUBLE PRECISION,
    "Longitud MM" DOUBLE PRECISION,
    "Ancho M" DOUBLE PRECISION,
    "Ancho MM" DOUBLE PRECISION,
    "Alto M" DOUBLE PRECISION,
    "Altura MM" DOUBLE PRECISION,
    "Volumen DM3" DOUBLE PRECISION,
    "CM3" DOUBLE PRECISION,
    "Serie_familia_1" TEXT,
    "Familia_WEB" TEXT,
    "Familia_Catalogo" TEXT,
    "Familia_Catalogo_PTL" TEXT,
    "imagen" TEXT,
    "Url_ficha_tec" TEXT,
    "descontinuado" INTEGER,
    "descripcion_corta" TEXT,
    "img_url" TEXT,
    "PVP_26_01_26" DOUBLE PRECISION,
    "bc3_descripcion_corta" TEXT,
    "bc3_descripcion_larga" TEXT,
    "bc3_product_type" TEXT,
    "bc3_processed_at" TIMESTAMP,
    "bc3_descripcion_completa" TEXT
);

CREATE TABLE IF NOT EXISTS bc3_enrichment_jobs (
    job_id TEXT PRIMARY KEY,
    idempotency_key TEXT NOT NULL UNIQUE,
    request_hash TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed')),
    source_snapshot_id TEXT,
    requested_by TEXT,
    total_items INTEGER NOT NULL DEFAULT 0,
    updated_items INTEGER NOT NULL DEFAULT 0,
    unchanged_items INTEGER NOT NULL DEFAULT 0,
    missing_items INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS bc3_enrichment_job_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id TEXT NOT NULL REFERENCES bc3_enrichment_jobs(job_id),
    codigo TEXT NOT NULL,
    bc3_descripcion_corta TEXT,
    bc3_descripcion_larga TEXT,
    bc3_descripcion_completa TEXT,
    bc3_product_type TEXT,
    source_pdf_hash TEXT,
    ai_model TEXT,
    confidence DOUBLE PRECISION,
    result_status TEXT NOT NULL CHECK (
        result_status IN ('pending', 'updated', 'unchanged', 'missing', 'failed')
    ),
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_bc3_enrichment_job_items_job_id_codigo UNIQUE (job_id, codigo)
);

    -- Compatibility for migration/03, whose integer id column had no generator.
    -- Keep existing rows and make this safe to re-run after migration/04.
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM pg_attribute AS attribute
            WHERE attribute.attrelid = 'bc3_enrichment_job_items'::regclass
              AND attribute.attname = 'id'
              AND NOT attribute.attisdropped
              AND attribute.attidentity = ''
              AND NOT EXISTS (
                  SELECT 1
                  FROM pg_attrdef AS default_value
                  WHERE default_value.adrelid = attribute.attrelid
                    AND default_value.adnum = attribute.attnum
              )
        ) THEN
            ALTER TABLE bc3_enrichment_job_items
                ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        END IF;
    END $$;

    CREATE INDEX IF NOT EXISTS ix_bc3_enrichment_jobs_idempotency_key
        ON bc3_enrichment_jobs (idempotency_key);
CREATE INDEX IF NOT EXISTS ix_bc3_enrichment_jobs_status_created_at
    ON bc3_enrichment_jobs (status, created_at);
CREATE INDEX IF NOT EXISTS ix_bc3_enrichment_job_items_job_id_codigo
    ON bc3_enrichment_job_items (job_id, codigo);

DO $$
BEGIN
    IF to_regclass('productos_clean') IS NOT NULL THEN
        IF EXISTS (
            SELECT 1
            FROM pg_attribute
            WHERE attrelid = 'productos_clean'::regclass
              AND attname = 'RAEE_A'
              AND NOT attisdropped
        ) THEN
            ALTER VIEW productos_clean RENAME COLUMN "RAEE_A" TO raee_a;
        END IF;
        IF EXISTS (
            SELECT 1
            FROM pg_attribute
            WHERE attrelid = 'productos_clean'::regclass
              AND attname = 'RAEE_L'
              AND NOT attisdropped
        ) THEN
            ALTER VIEW productos_clean RENAME COLUMN "RAEE_L" TO raee_l;
        END IF;
        IF EXISTS (
            SELECT 1
            FROM pg_attribute
            WHERE attrelid = 'productos_clean'::regclass
              AND attname = 'RAEE_T'
              AND NOT attisdropped
        ) THEN
            ALTER VIEW productos_clean RENAME COLUMN "RAEE_T" TO raee_t;
        END IF;
    END IF;
END $$;

CREATE OR REPLACE VIEW productos_clean AS
SELECT
    "CÓDIGO" AS codigo,
    "DESCRIPCION" AS descripcion,
    "MARCA" AS marca,
    "Familia_WEB" AS familia,
    "descripcion_corta" AS descripcion_corta,
    "PVP_26_01_26" AS pvp,
    "bc3_descripcion_corta" AS bc3_descripcion_corta,
    "bc3_descripcion_completa" AS bc3_descripcion_completa,
    "bc3_descripcion_larga" AS bc3_descripcion_larga,
    "bc3_product_type" AS bc3_product_type,
    "bc3_processed_at" AS bc3_processed_at,
    "CÓDIGO WEB" AS codigo_web,
    "REFERENCIA" AS referencia,
    "EAN 13" AS ean_13,
    "imagen" AS imagen,
    "img_url" AS img_url,
    "RAEE_A" AS raee_a,
    "RAEE_L" AS raee_l,
    "RAEE_T" AS raee_t
FROM "productos";
