CREATE TABLE IF NOT EXISTS bc3_enrichment_previews (
    preview_id TEXT PRIMARY KEY,
    payload_hash TEXT NOT NULL,
    canonical_payload TEXT NOT NULL,
    source_snapshot_id TEXT NOT NULL,
    actor_id TEXT NOT NULL,
    scope TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'approved', 'used', 'expired')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    approval_actor_id TEXT,
    github_repository TEXT NOT NULL,
    github_pr_number INTEGER NOT NULL,
    github_head_sha TEXT NOT NULL,
    github_approval_count INTEGER,
    github_approval_verified_at TIMESTAMP,
    used_at TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_bc3_enrichment_previews_expires_status
    ON bc3_enrichment_previews (expires_at, status);
CREATE TABLE IF NOT EXISTS bc3_enrichment_preview_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preview_id TEXT NOT NULL REFERENCES bc3_enrichment_previews(preview_id),
    codigo TEXT NOT NULL,
    current_values JSON NOT NULL,
    proposed_values JSON NOT NULL,
    UNIQUE(preview_id, codigo)
);
ALTER TABLE bc3_enrichment_previews ADD COLUMN IF NOT EXISTS github_repository TEXT;
ALTER TABLE bc3_enrichment_previews ADD COLUMN IF NOT EXISTS github_pr_number INTEGER;
ALTER TABLE bc3_enrichment_previews ADD COLUMN IF NOT EXISTS github_head_sha TEXT;
ALTER TABLE bc3_enrichment_previews ADD COLUMN IF NOT EXISTS github_approval_count INTEGER;
ALTER TABLE bc3_enrichment_previews ADD COLUMN IF NOT EXISTS github_approval_verified_at TIMESTAMP;
ALTER TABLE bc3_enrichment_jobs ADD COLUMN IF NOT EXISTS actor_id TEXT;
ALTER TABLE bc3_enrichment_jobs ADD COLUMN IF NOT EXISTS preview_id TEXT;
    ALTER TABLE bc3_enrichment_job_items ADD COLUMN IF NOT EXISTS before_values JSON;
    ALTER TABLE bc3_enrichment_job_items ADD COLUMN IF NOT EXISTS after_values JSON;
    ALTER TABLE bc3_enrichment_job_items ADD COLUMN IF NOT EXISTS bc3_descripcion_corta_ca TEXT;
    ALTER TABLE bc3_enrichment_job_items ADD COLUMN IF NOT EXISTS bc3_descripcion_larga_ca TEXT;
    ALTER TABLE bc3_enrichment_job_items ADD COLUMN IF NOT EXISTS bc3_descripcion_corta_gl TEXT;
    ALTER TABLE bc3_enrichment_job_items ADD COLUMN IF NOT EXISTS bc3_descripcion_larga_gl TEXT;

    -- Legacy installations have an integer primary key but no generator. Add
    -- identity in place, retaining rows. Existing valid generators are kept.
    DO $$
    DECLARE
        target_table TEXT;
        id_default TEXT;
        id_identity TEXT;
        sequence_name TEXT;
        maximum_id BIGINT;
        sequence_last BIGINT;
    BEGIN
        FOREACH target_table IN ARRAY ARRAY[
            'bc3_enrichment_job_items', 'bc3_enrichment_preview_items'
        ] LOOP
            SELECT c.column_default, c.identity_generation
              INTO id_default, id_identity
              FROM information_schema.columns AS c
             WHERE c.table_schema = current_schema()
               AND c.table_name = target_table
               AND c.column_name = 'id';
            IF NOT FOUND THEN
                RAISE EXCEPTION 'Cannot upgrade %.id: column is missing', target_table;
            END IF;

            IF id_identity IS NULL AND id_default IS NULL THEN
                EXECUTE format(
                    'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
                    target_table
                );
            ELSIF id_identity IS NULL AND pg_get_serial_sequence(target_table, 'id') IS NULL THEN
                RAISE EXCEPTION
                    'Cannot upgrade %.id: existing default is not backed by a sequence',
                    target_table;
            END IF;

            sequence_name := pg_get_serial_sequence(target_table, 'id');
            IF sequence_name IS NULL THEN
                RAISE EXCEPTION 'Cannot upgrade %.id: generator sequence is missing', target_table;
            END IF;

            EXECUTE format('SELECT max(id) FROM %I', target_table) INTO maximum_id;
            -- Empty tables need no reset. Existing sequences must not move backwards.
            IF maximum_id IS NOT NULL THEN
                EXECUTE format('SELECT last_value FROM %s', sequence_name::regclass)
                   INTO sequence_last;
                IF sequence_last IS NULL OR sequence_last < maximum_id THEN
                    PERFORM setval(sequence_name::regclass, GREATEST(maximum_id, 1), true);
                END IF;
            END IF;
        END LOOP;
    END $$;


    -- Existing deployments created these audit columns as TEXT before the ORM
    -- contract declared them as JSON. Convert only when necessary, so repeats
    -- are true no-ops while malformed legacy JSON fails closed.
    DO $$
    DECLARE
        target_table TEXT;
        target_column TEXT;
        data_type TEXT;
    BEGIN
        FOREACH target_table IN ARRAY ARRAY[
            'bc3_enrichment_preview_items', 'bc3_enrichment_job_items'
        ] LOOP
            FOREACH target_column IN ARRAY ARRAY[
                'current_values', 'proposed_values', 'before_values', 'after_values'
            ] LOOP
                SELECT c.udt_name INTO data_type
                  FROM information_schema.columns AS c
                 WHERE c.table_schema = current_schema()
                   AND c.table_name = target_table
                   AND c.column_name = target_column;
                IF FOUND AND data_type <> 'json' THEN
                    EXECUTE format(
                        'ALTER TABLE %I ALTER COLUMN %I TYPE JSON USING %I::JSON',
                        target_table, target_column, target_column
                    );
                END IF;
            END LOOP;
        END LOOP;
    END $$;
