[mypy]
python_version = 3.14
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
ignore_missing_imports = True

[mypy-app.domain.*]
disallow_untyped_defs = True
warn_return_any = True

[mypy-app.application.*]
disallow_untyped_defs = True
warn_return_any = True

[mypy-app.infrastructure.*]
ignore_errors = True

[mypy-app.interfaces.*]
disallow_untyped_defs = True

[mypy-app.routers.*]
ignore_errors = True

[mypy-app.security.*]
ignore_errors = True

