# pyright: reportMissingImports=false
from __future__ import annotations

import hashlib
import json
import sqlite3
from contextlib import contextmanager
from datetime import datetime
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest

from migration.local_backup import BackupError, normalize_local_postgres_url
from migration.postgres_local_migrate import (  # pyright: ignore[reportMissingImports]
    PRODUCT_COLUMNS,
    VerificationError,
    _open_source_snapshot,
    _read_batches,
    canonical_row_hash,
    compare_sorted_keys,
    discover_source_metadata,
    import_products,
    main,
    parse_args,
    require_verified_postgres_backup,
    validate_local_postgres_url,
    verify_source_target_rows,
)

ROOT = Path(__file__).parents[2]
SCHEMA_PATH = ROOT / "migration" / "04_postgres_schema.sql"


def test_schema_declares_products_jobs_and_safe_view() -> None:
    sql = SCHEMA_PATH.read_text(encoding="utf-8")

    assert 'CREATE TABLE IF NOT EXISTS "productos"' in sql
    assert len(PRODUCT_COLUMNS) == 40
    assert '"CÓDIGO" TEXT PRIMARY KEY' in sql
    assert "CREATE TABLE IF NOT EXISTS bc3_enrichment_jobs" in sql
    assert "CREATE TABLE IF NOT EXISTS bc3_enrichment_job_items" in sql
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "CREATE OR REPLACE VIEW productos_clean" in sql
    assert '"RAEE_A" AS raee_a' in sql
    assert '"RAEE_L" AS raee_l' in sql
    assert '"RAEE_T" AS raee_t' in sql
    assert "DROP TABLE" not in sql.upper()


def test_schema_contains_id_generator_compatibility_block() -> None:
    sql = SCHEMA_PATH.read_text(encoding="utf-8")

    assert "attidentity" in sql
    assert "pg_attrdef" in sql
    assert "ADD GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "ALTER TABLE bc3_enrichment_job_items" in sql
    assert "TRUNCATE" not in sql.upper()


def test_argument_validation_requires_expected_cli_options(tmp_path: Path) -> None:
    args = parse_args(
        [
            "--sqlite-path",
            str(tmp_path / "source.db"),
            "--postgres-url",
            "postgresql://localhost/api_disano_local",
            "--batch-size",
            "100",
            "--dry-run",
        ]
    )

    assert args.sqlite_path == tmp_path / "source.db"
    assert args.batch_size == 100
    assert args.dry_run is True

    with pytest.raises(SystemExit):
        parse_args(["--sqlite-path", str(tmp_path / "source.db")])


def test_dry_run_remains_available_without_backup(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.setattr(
        "migration.postgres_local_migrate._load_source",
        lambda _: (PRODUCT_COLUMNS, 0),
    )

    assert (
        main(
            [
                "--sqlite-path",
                str(tmp_path / "source.db"),
                "--postgres-url",
                "postgresql://localhost/api_disano_local",
                "--dry-run",
            ]
        )
        == 0
    )
    assert "Dry run" in capsys.readouterr().out


def test_non_local_postgres_host_is_refused() -> None:
    with pytest.raises(ValueError, match="local PostgreSQL"):
        validate_local_postgres_url("postgresql://db.example.invalid/api_disano_local")


def test_local_postgres_hosts_are_accepted() -> None:
    for host in ("localhost", "127.0.0.1", "[::1]"):
        validate_local_postgres_url(f"postgresql://{host}/api_disano_local")


def test_migration_url_validation_matches_backup_normalizer() -> None:
    url = "postgresql+psycopg://user:secret@localhost:5433/api_disano_local"

    validate_local_postgres_url(url)
    assert normalize_local_postgres_url(url)[0].startswith(
        "postgresql+psycopg://user@localhost:5433/"
    )


@pytest.mark.parametrize(
    "url",
    [
        "postgresql://localhost:0/api_disano_local",
        "postgresql://localhost:65536/api_disano_local",
        "postgresql://localhost:not-a-port/api_disano_local",
        "postgresql:///api_disano_local",
        "mysql://localhost:5432/api_disano_local",
    ],
)
def test_invalid_local_postgres_urls_are_refused(url: str) -> None:
    with pytest.raises(ValueError):
        validate_local_postgres_url(url)


def test_missing_backup_artifact_fails_closed_with_stable_error(
    tmp_path: Path,
) -> None:
    with pytest.raises(BackupError, match="Backup artifact is missing or unreadable"):
        require_verified_postgres_backup(tmp_path / "missing.dump", tmp_path / "missing.dump.json")


def test_import_rejects_non_loopback_url_before_connecting(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(
        "migration.postgres_local_migrate.require_verified_postgres_backup",
        lambda *_: None,
    )
    monkeypatch.setattr(
        "migration.postgres_local_migrate._connect_postgres",
        lambda _: pytest.fail("non-loopback PostgreSQL connection must not start"),
    )

    with pytest.raises(ValueError, match="local PostgreSQL"):
        import_products(
            tmp_path / "source.db",
            "postgresql://db.example.invalid/api_disano_local",
            100,
        )


def test_import_requires_verified_postgres_backup_before_connecting(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(
        "migration.postgres_local_migrate._connect_postgres",
        lambda _: pytest.fail("PostgreSQL connection must not start without a backup"),
    )

    with pytest.raises(BackupError, match="verified PostgreSQL backup"):
        import_products(
            tmp_path / "source.db",
            "postgresql://localhost/api_disano_local",
            100,
        )


def test_import_accepts_verified_postgres_backup_artifact(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    backup = tmp_path / "postgres.dump"
    backup.write_bytes(b"verified local test artifact")
    monkeypatch.setattr("migration.local_backup.shutil_which", lambda _: "/usr/bin/pg_restore")

    def fake_pg_restore(command: list[str], **kwargs: Any) -> SimpleNamespace:
        assert command == ["pg_restore", "--list", str(backup)]
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr("migration.local_backup.subprocess.run", fake_pg_restore)
    manifest = tmp_path / "postgres.dump.json"
    manifest.write_text(
        json.dumps(
            {
                "format": "postgresql-custom",
                "backup": backup.name,
                "sha256": hashlib.sha256(backup.read_bytes()).hexdigest(),
            }
        ),
        encoding="utf-8",
    )
    require_verified_postgres_backup(backup, manifest)


def test_import_rejects_unverified_postgres_backup(tmp_path: Path) -> None:
    backup = tmp_path / "postgres.dump"
    backup.write_bytes(b"original artifact")
    manifest = tmp_path / "postgres.dump.json"
    manifest.write_text(
        json.dumps(
            {
                "format": "postgresql-custom",
                "backup": backup.name,
                "sha256": hashlib.sha256(backup.read_bytes()).hexdigest(),
            }
        ),
        encoding="utf-8",
    )
    backup.write_bytes(b"tampered artifact")

    with pytest.raises(BackupError, match="verified PostgreSQL backup"):
        require_verified_postgres_backup(backup, manifest)


def test_source_metadata_discovery_reads_exact_product_columns(tmp_path: Path) -> None:
    database_path = tmp_path / "source.db"
    with sqlite3.connect(database_path) as connection:
        connection.execute('CREATE TABLE productos ("CÓDIGO" TEXT PRIMARY KEY, MARCA TEXT)')
        metadata = discover_source_metadata(database_path)

        assert metadata == ["CÓDIGO", "MARCA"]
        assert set(metadata) <= set(PRODUCT_COLUMNS)


def test_canonical_row_hash_distinguishes_null_and_empty_string() -> None:
    assert canonical_row_hash((None,)) != canonical_row_hash(("",))
    assert canonical_row_hash(("a", 1, True)) == canonical_row_hash(("a", 1, True))


def test_canonical_row_hash_rejects_unsupported_values() -> None:
    with pytest.raises(VerificationError, match="unsupported"):
        canonical_row_hash((object(),))


def test_compare_sorted_keys_reports_null_duplicates_missing_and_extra() -> None:
    result = compare_sorted_keys([None, "a", "a", "c"], ["a", "b"])

    assert result.null_source_keys == 1
    assert result.duplicate_source_keys == 1
    assert result.missing_target_keys == 2
    assert result.extra_target_keys == 1


def test_verify_source_target_rows_detects_content_digest_mismatch() -> None:
    result = verify_source_target_rows([("a", "value")], [("a", "changed")])

    assert result.content_digest_mismatches == 1
    assert result.missing_target_keys == 0
    assert result.extra_target_keys == 0


def test_verify_source_target_rows_accepts_equivalent_sqlite_timestamp() -> None:
    result = verify_source_target_rows(
        [("a", "2026-08-14T17:13:30")],
        [("a", datetime(2026, 8, 14, 17, 13, 30))],
    )

    assert result.is_valid


@pytest.mark.parametrize(
    "source_value,target_value",
    [
        ("2026-08-14T17:13:30", datetime(2026, 8, 14, 17, 13, 31)),
        (None, ""),
        ("", None),
    ],
)
def test_verify_source_target_rows_distinguishes_non_equivalent_values(
    source_value: object, target_value: object
) -> None:
    result = verify_source_target_rows([("a", source_value)], [("a", target_value)])

    assert result.content_digest_mismatches == 1


class _ClosedAfterContextConnection:
    closed = False

    def __init__(self) -> None:
        self.rollback_calls = 0

    def __enter__(self) -> "_ClosedAfterContextConnection":
        return self

    def __exit__(self, *_: object) -> bool:
        self.closed = True
        return False

    def cursor(self) -> "_FailingCursor":
        return _FailingCursor()

    def rollback(self) -> None:
        self.rollback_calls += 1
        raise AssertionError("rollback must not run after the connection closes")

    def close(self) -> None:
        self.closed = True


class _FailingCursor:
    def __enter__(self) -> "_FailingCursor":
        return self

    def __exit__(self, *_: object) -> bool:
        return False

    def execute(self, *_: object) -> None:
        return None

    def executemany(self, *_: object) -> None:
        return None


@contextmanager
def _fake_source_snapshot(_: Path):
    yield PRODUCT_COLUMNS, 0, object()


def test_import_products_does_not_rollback_closed_connection(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    connection = _ClosedAfterContextConnection()
    monkeypatch.setattr(
        "migration.postgres_local_migrate.require_verified_postgres_backup",
        lambda *_: None,
    )
    monkeypatch.setattr(
        "migration.postgres_local_migrate._connect_postgres",
        lambda _: connection,
    )
    monkeypatch.setattr(
        "migration.postgres_local_migrate._open_source_snapshot",
        _fake_source_snapshot,
    )
    monkeypatch.setattr(
        "migration.postgres_local_migrate._read_batches",
        lambda *_: (_ for _ in ()).throw(RuntimeError("batch failed")),
    )

    with pytest.raises(RuntimeError, match="batch failed"):
        import_products(tmp_path / "source.db", "postgresql://localhost/db", 1)

    assert connection.rollback_calls == 0


def test_verify_source_target_rows_uses_bounded_streaming_comparison() -> None:
    result = verify_source_target_rows(
        ((key, key) for key in ("a", "b")),
        ((key, key) for key in ("a", "b")),
    )

    assert result.is_valid


def test_source_snapshot_keeps_count_and_batches_consistent_during_mutation(
    tmp_path: Path,
) -> None:
    database_path = tmp_path / "source.db"
    columns_sql = ", ".join(f'"{column}" TEXT' for column in PRODUCT_COLUMNS)
    values: list[object | None] = [None] * len(PRODUCT_COLUMNS)
    values[1] = "A-1"
    values[5] = "original"
    placeholders = ", ".join("?" for _ in PRODUCT_COLUMNS)
    with sqlite3.connect(database_path) as connection:
        connection.execute("PRAGMA journal_mode=WAL")
        connection.execute(f"CREATE TABLE productos ({columns_sql})")
        connection.execute(f"INSERT INTO productos VALUES ({placeholders})", values)
        connection.commit()

    with _open_source_snapshot(database_path) as (_, source_count, snapshot):
        assert source_count == 1
        with sqlite3.connect(database_path) as mutator:
            mutator.execute(
                'UPDATE productos SET "DESCRIPCION" = ? WHERE "CÓDIGO" = ?',
                ("mutated", "A-1"),
            )
            mutator.commit()

        rows = list(_read_batches(snapshot, 1))

    assert rows[0][0][5] == "original"
